services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    working_dir: /var/www
    ports:
      - "8888:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:8.4
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=creative
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8404:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    restart: always
    ports:
      - "8405:80"  # Новый внешний порт для доступа в браузере
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
